### ISSUE TITLE
java.lang.InstantiationException: class has no zero argument constructor

### ISSUE THREAD

**Issue by jskierbi** [jskierbi/cupboard-kotlin#1]
There's a problem with reading Kotlin data classes with no default constructor when there's no ```val``` field (only ```var``` fields):
```
  @Keep
  data class LineUpData(var _id: Long?,
                        var index: Int,
                        var content: String)
```

Following exception is produced:
```
java.lang.InstantiationException: java.lang.Class<LineUpData> has no zero argument constructor
at java.lang.Class.newInstance(Native Method)
at com.jskierbi.cupboardkotlin.KotlinReflectiveEntityConverter.fromCursor(KotlinReflectiveEntityConverter.kt:85)
at ...
at de.neofonie.commons.cupboard.CupboardRepo.get(CupboardRepo.kt:13)
```

Seems that library doesn't recognise Kotlin primary ctor for some reason - I recon problem is here: https://github.com/jskierbi/cupboard-kotlin/blob/master/cupboard-kotlin/src/main/java/com/jskierbi/cupboardkotlin/KotlinReflectiveEntityConverter.kt#L56

**Comment by jskierbi** [comment]
[](url)
